version: '3.4'
services:
  db:
    image: postgres
    container_name: postgresql-db
    ports:
      - 5432:5432
    env_file:
      - config/db.env
    networks:
      - accounts
    volumes:
      - pgdata:/var/lib/postgresql/data

  service:
    depends_on:
      - db
    build: .
    container_name: accounts-service
    ports:
      - "8080:8080"
    restart: always
    networks:
      - accounts

volumes:
  pgdata: {}

networks:
  accounts: