spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:account-transaction}?serverTimeZone=UTC}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:pgadmin}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
