spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account-transaction?serverTimeZone=UTC
    username: postgres
    password: pgadmin

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true
